<?php
/**
 * Created by PhpStorm.
 * User: thang
 * Date: 03/02/2018
 * Time: 08:12
 */
namespace Test\Das\Controller\Adminhtml\Subscription;

use Magento\Framework\App\Action\Action;

class Form extends Action {
    public function execute()
    {
        // TODO: Implement execute() method.
        $sub = $this->_objectManager->create('Test\Das\Model\Subscription');
        $data = $this->getRequest()->getPost();
        if ($data['action'] =='delete') {
            $sub = load($data['id1']);
            $sub->delete();
            $this->getResponse()->setBody($data['action']);
        }
        else {
            $id = $data['id'];
            if ($id == '') {
                $array = [
                    'lastname' => $data['lastname'],
                    'firstname' => $data['firstname'],
                    'email' => $data['email'],
                    'status' => $data['status']];
            } else {
//            $sql = "Update" . $tableName . "set
//             firstname = $data[firstname],
//             lastname = $data[lastname],
//             email = $data[email],
//             status = $data[status]
//              where subscription_id = $id";
//            $connection->query($sql);
                $sub->load($id);
                $array = [
                    'subscription_id' => $id,
                    'lastname' => $data['lastname'],
                    'firstname' => $data['firstname'],
                    'email' => $data['email'],
                    'status' => $data['status']];
            }
            $sub->addData($array);
            $sub->save();
//        $this->_redirect('http://localhost/m218/admin/das/subscription');
        }
    }
    protected  function  _isAllowed()
    {
        // TODO: Change the autogenerated stub
        return $this->_authorization->isAllowed('Test_Das::index');
    }
}
