<?php
/**
 * Created by PhpStorm.
 * User: thang
 * Date: 02/02/2018
 * Time: 23:11
 */
namespace Test\Das\Controller\Adminhtml\Subscription;

use Magento\Backend\App\Action;
use Magento\Framework\View\Result\PageFactory;

class Index extends Action{
    protected $resultPageFactory;
    public function __construct(Action\Context $context, PageFactory $resultPageFactory)
    {
        parent::__construct($context);
        $this->resultPageFactory = $resultPageFactory;
    }
    public function execute()
    {
        // TODO: Implement execute() method.
        $resultPage = $this->resultPageFactory->create();
//        $resultPage->setActiveMenu('Test_Das::sub');
//        $resultPage->addBreadcrumb(__('Tes'),__('Test'));
//        $resultPage->addBreadCrumb(__('Manage Subscription'),__('Manage Subscription'));
        return $resultPage;
    }
    protected  function  _isAllowed()
    {
        // TODO: Change the autogenerated stub
        return $this->_authorization->isAllowed('Test_Das::sub');
    }
}